sudo: required
language: generic
services:
    - docker
before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t johnahn/docker-react-app -f Dockerfile.dev .
script:
    - docker run -e CI=true johnahn/docker-react-app npm run test -- --coverage
after-success:
    - echo "Test Success"